### ISSUE TITLE
Reader part is not working as it should

### ISSUE THREAD

**Issue by oya163** [ironSource/parquetjs#69]
I received the following error while testing with **reader.js**. I created **fruits.parquet** using **writer.js** from the example.

```
(node:21836) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'num_values' of null
    at decodeDataPage (/home/ubuntu/memNode/node_modules/parquetjs/lib/reader.js:312:44)
    at decodeDataPages (/home/ubuntu/memNode/node_modules/parquetjs/lib/reader.js:301:20)
    at ParquetEnvelopeReader.readColumnChunk (/home/ubuntu/memNode/node_modules/parquetjs/lib/reader.js:245:12)
(node:21836) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21836) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by ZJONSSON** [comment]
Can you past the exact code you ran?    Did you close the writer after writing data?

**Comment by oya163** [comment]
It is the exact same code of **writer.js** from examples folder.

**Comment by luoxlgh** [comment]
same trouble. Have you resolve the problem?

**Comment by ZJONSSON** [comment]
What node version?    It's important that you are on a version that supports `async/await`

**Comment by fzaffarana** [comment]
same problem with node v8.4.0
